### ISSUE TITLE
Why TTL value is string instead of number

### ISSUE THREAD

**Issue by NafieAlhilaly** [0ss/mmry#1]
Hey, cool project 👋🤓

I was exploring your project and came across 
https://github.com/0ss/mmry/blob/b22e632d208630fb2bc4e39cf2b990148eac460f/src/index.ts#L15

and wondered 🤔 why did you choose to give `ttlString` the type of string instead of a number.

using numbers can reduce confusion and make you avoid the string parsing headache.

Best of luck.

**Comment by 0ss** [comment]
Hey! Thanks for pointing it out, a lot of memory cache libraries in Nodejs go with the approach of saving the `TTL` as a number in `ms`.

However, I found this to be problematic in some cases (still not a big deal), as such, when you want to save a value for a long time the `TTL` value will be a large number.

Yes, the `ttlString` approach has a parsing headache, but easier to deal with for us, humans.

**Comment by NafieAlhilaly** [comment]
I don't think saving a big number would be an issue, as long as you are staying consistent across the codebase and with other caching tools, preferring consistency over `easier to deal with` .

Remember you do not have to stick with `ms`, you can accept `seconds` (Redis use seconds) and then change it to `ms` behind the scene.

**Comment by 0ss** [comment]
Sure, will be considered 👍
